curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=1" >   gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=2" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=3" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=4" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=5" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=6" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=7" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/issues?per_page=100&page=8" >>  gno.issues.json
curl "https://api.github.com/repos/gnolang/gno/pulls?per_page=100&page=1" >   gno.pulls.json
curl "https://api.github.com/repos/gnolang/gno/pulls?per_page=100&page=2" >>  gno.pulls.json
curl "https://api.github.com/repos/gnolang/gno/pulls?per_page=100&page=3" >>  gno.pulls.json
